/**
 * New node file
 */

/* command tags */
const UNKNOWN_COMMAND_RESPONSE=0x7FFF;

const PUBLIC_LOGIN_REQUEST=0xC001;
const PUBLIC_LOGIN_RESPONSE=0x4001;
const SCRAMBLED_LOGIN_REQUEST=0xC002;
const SCRAMBLED_LOGIN_RESPONSE=0x4002;
const MULTI_PUBLIC_LOGIN_REQUEST=0xC009;
const MULTI_PUBLIC_LOGIN_RESPONSE=0x4009;
const MULTI_SCRAMBLED_LOGIN_REQUEST=0xC00A;
const MULTI_SCRAMBLED_LOGIN_RESPONSE=0x400A;
const LOGOUT_RESPONSE=0x4004;

const MAINTENANCE_REQUEST=0xC003;
const MAINTENANCE_RESPONSE=0x4003;

const PUSH_CHANNEL_OPEN_REQUEST=0x9000;
const PUSH_CHANNEL_OPEN_RESPONSE=0x1000;
const PUSH_CHANNEL_CLOSE_REQUEST=0x9001;
const PUSH_CHANNEL_CLOSE_RESPONSE=0x1001;
const PUSH_DATA_TRANSFER_REQUEST=0x9002;
const PUSH_DATA_TRANSFER_RESPONSE=0x1002;
const PUSH_TARGET_NAMELIST_REQUEST=0xA008;
const PUSH_TARGET_NAMELIST_RESPONSE=0x2008;
const PUSH_TARGET_REGISTER_REQUEST=0xC005;
const PUSH_TARGET_REGISTER_RESPONSE=0x4005;
const PUSH_TARGET_DEREGISTER_REQUEST=0xC006;
const PUSH_TARGET_DEREGISTER_RESPONSE=0x4006;

 const CONNECTION_OPEN_REQUEST=0x9003;
 const CONNECTION_OPEN_RESPONSE=0x1003;
 const CONNECTION_CLOSE_REQUEST=0x9004;
 const CONNECTION_CLOSE_RESPONSE=0x1004;

 const NETWORK_STATUS_REQUEST=0xA004;
 const NETWORK_STATUS_RESPONSE=0x2004;

 const PROTOCOL_VERSION_REQUEST=0xA000;
 const PROTOCOL_VERSION_RESPONSE=0x2000;

 const DEVICE_IDENTIFIER_REQUEST=0xA003;
 const DEVICE_IDENTIFIER_RESPONSE=0x2003;
 const DEVICE_AUTHENTICATION_REQUEST=0xA006;
 const DEVICE_AUTHENTICATION_RESPONSE=0x2006;
 const DEVICE_TIME_REQUEST=0xA007;
 const DEVICE_TIME_RESPONSE=0x2007;
 const DEVICE_SOFTWARE_REQUEST=0xA001;
 const DEVICE_SOFTWARE_RESPONSE=0x2001;

 const IP_STATISTIC_REQUEST=0xA005;
 const IP_STATISTIC_RESPONSE=0x2005;

 const TRACEROUTE_REQUEST=0xA00A;
 const TRACEROUTE_RESPONSE=0x200A;

 const SERVER_MODE_REQUEST=0xC010;
 const SERVER_MODE_RESPONSE=0x4010;
 const SERVER_MODE_RECONNECT_REQUEST=0xC011;
 const SERVER_MODE_RECONNECT_RESPONSE=0x4011;

 const STREAM_SOURCE_REGISTER_REQUEST=0xC00B;
 const STREAM_SOURCE_REGISTER_RESPONSE=0x400B;
 const STREAM_SOURCE_DEREGISTER_REQUEST=0xC00C;
 const STREAM_SOURCE_DEREGISTER_RESPONSE=0x400C;
 const STREAM_CHANNEL_OPEN_REQUEST=0x9006;
 const STREAM_CHANNEL_OPEN_RESPONSE=0x1006;
 const STREAM_CHANNEL_CLOSE_REQUEST=0x9007;
 const STREAM_CHANNEL_CLOSE_RESPONSE=0x1007;
 const STREAM_DATA_TRANSFER_REQUEST=0x9008;
 const STREAM_DATA_TRANSFER_RESPONSE=0x1008;

 const DATA_TRANSFER_REQUEST=0x9005;
 const DATA_TRANSFER_RESPONSE=0x1005;

/* Watchdog Message Tags */
 const WTG_REQUEST=0xC008;
 const WTG_RESPONSE=0x4008;

 const ESCAPE_SEQUENCE=0x1b;
 
 const DEFAULT_SCRAMBLE_KEY = new Buffer("0102030405060708090001020304050607080900010203040506070809000001","hex");
 
 const MAX_BUFFER_SIZE = 512;
 
module.exports = {
		UNKNOWN_COMMAND_RESPONSE: UNKNOWN_COMMAND_RESPONSE,
		PUBLIC_LOGIN_REQUEST: PUBLIC_LOGIN_REQUEST,
		PUBLIC_LOGIN_RESPONSE: PUBLIC_LOGIN_RESPONSE,
		SCRAMBLED_LOGIN_REQUEST: SCRAMBLED_LOGIN_REQUEST,
		SCRAMBLED_LOGIN_RESPONSE: SCRAMBLED_LOGIN_RESPONSE,
		MULTI_PUBLIC_LOGIN_REQUEST: MULTI_PUBLIC_LOGIN_REQUEST,
		MULTI_PUBLIC_LOGIN_RESPONSE: MULTI_PUBLIC_LOGIN_RESPONSE,
		MULTI_SCRAMBLED_LOGIN_REQUEST: MULTI_SCRAMBLED_LOGIN_REQUEST,
		MULTI_SCRAMBLED_LOGIN_RESPONSE: MULTI_SCRAMBLED_LOGIN_RESPONSE,
		LOGOUT_RESPONSE: LOGOUT_RESPONSE,

		MAINTENANCE_REQUEST: MAINTENANCE_REQUEST,
		MAINTENANCE_RESPONSE: MAINTENANCE_RESPONSE,

		PUSH_CHANNEL_OPEN_REQUEST: PUSH_CHANNEL_OPEN_REQUEST,
		PUSH_CHANNEL_OPEN_RESPONSE: PUSH_CHANNEL_OPEN_RESPONSE,
		PUSH_CHANNEL_CLOSE_REQUEST: PUSH_CHANNEL_CLOSE_REQUEST,
		PUSH_CHANNEL_CLOSE_RESPONSE: PUSH_CHANNEL_CLOSE_RESPONSE,
		PUSH_DATA_TRANSFER_REQUEST: PUSH_DATA_TRANSFER_REQUEST,
		PUSH_DATA_TRANSFER_RESPONSE: PUSH_DATA_TRANSFER_RESPONSE,
		PUSH_TARGET_NAMELIST_REQUEST: PUSH_TARGET_NAMELIST_REQUEST,
		PUSH_TARGET_NAMELIST_RESPONSE: PUSH_TARGET_NAMELIST_RESPONSE,
		PUSH_TARGET_REGISTER_REQUEST: PUSH_TARGET_REGISTER_REQUEST,
		PUSH_TARGET_REGISTER_RESPONSE: PUSH_TARGET_REGISTER_RESPONSE,
		PUSH_TARGET_DEREGISTER_REQUEST: PUSH_TARGET_DEREGISTER_REQUEST,
		PUSH_TARGET_DEREGISTER_RESPONSE: PUSH_TARGET_DEREGISTER_RESPONSE,

		CONNECTION_OPEN_REQUEST: CONNECTION_OPEN_REQUEST,
		CONNECTION_OPEN_RESPONSE: CONNECTION_OPEN_RESPONSE,
		CONNECTION_CLOSE_REQUEST: CONNECTION_CLOSE_REQUEST,
		CONNECTION_CLOSE_RESPONSE: CONNECTION_CLOSE_RESPONSE,

		NETWORK_STATUS_REQUEST: NETWORK_STATUS_REQUEST,
		NETWORK_STATUS_RESPONSE: NETWORK_STATUS_RESPONSE,

		PROTOCOL_VERSION_REQUEST: PROTOCOL_VERSION_REQUEST,
		PROTOCOL_VERSION_RESPONSE: PROTOCOL_VERSION_RESPONSE,

		DEVICE_IDENTIFIER_REQUEST: DEVICE_IDENTIFIER_REQUEST,
		DEVICE_IDENTIFIER_RESPONSE: DEVICE_IDENTIFIER_RESPONSE,
		DEVICE_AUTHENTICATION_REQUEST: DEVICE_AUTHENTICATION_REQUEST,
		DEVICE_AUTHENTICATION_RESPONSE: DEVICE_AUTHENTICATION_RESPONSE,
		DEVICE_TIME_REQUEST: DEVICE_TIME_REQUEST,
		DEVICE_TIME_RESPONSE: DEVICE_TIME_RESPONSE,
		DEVICE_SOFTWARE_REQUEST: DEVICE_SOFTWARE_REQUEST,
		DEVICE_SOFTWARE_RESPONSE: DEVICE_SOFTWARE_RESPONSE,

		IP_STATISTIC_REQUEST: IP_STATISTIC_REQUEST,
		IP_STATISTIC_RESPONSE: IP_STATISTIC_RESPONSE,

		TRACEROUTE_REQUEST: TRACEROUTE_REQUEST,
		TRACEROUTE_RESPONSE: TRACEROUTE_RESPONSE,

		SERVER_MODE_REQUEST: SERVER_MODE_REQUEST,
		SERVER_MODE_RESPONSE: SERVER_MODE_RESPONSE,
		SERVER_MODE_RECONNECT_REQUEST: SERVER_MODE_RECONNECT_REQUEST,
		SERVER_MODE_RECONNECT_RESPONSE: SERVER_MODE_RECONNECT_RESPONSE,

		STREAM_SOURCE_REGISTER_REQUEST: STREAM_SOURCE_REGISTER_REQUEST,
		STREAM_SOURCE_REGISTER_RESPONSE: STREAM_SOURCE_REGISTER_RESPONSE,
		STREAM_SOURCE_DEREGISTER_REQUEST: STREAM_SOURCE_DEREGISTER_REQUEST,
		STREAM_SOURCE_DEREGISTER_RESPONSE: STREAM_SOURCE_DEREGISTER_RESPONSE,
		STREAM_CHANNEL_OPEN_REQUEST: STREAM_CHANNEL_OPEN_REQUEST,
		STREAM_CHANNEL_OPEN_RESPONSE: STREAM_CHANNEL_OPEN_RESPONSE,
		STREAM_CHANNEL_CLOSE_REQUEST: STREAM_CHANNEL_CLOSE_REQUEST,
		STREAM_CHANNEL_CLOSE_RESPONSE: STREAM_CHANNEL_CLOSE_RESPONSE,
		STREAM_DATA_TRANSFER_REQUEST: STREAM_DATA_TRANSFER_REQUEST,
		STREAM_DATA_TRANSFER_RESPONSE: STREAM_DATA_TRANSFER_RESPONSE,

		DATA_TRANSFER_REQUEST: DATA_TRANSFER_REQUEST,
		DATA_TRANSFER_RESPONSE: DATA_TRANSFER_RESPONSE,

		/* Watchdog Message Tags */
		WTG_REQUEST: WTG_REQUEST,
		WTG_RESPONSE: WTG_RESPONSE,

		ESCAPE_SEQUENCE: ESCAPE_SEQUENCE,
		
		DEFAULT_SCRAMBLE_KEY: DEFAULT_SCRAMBLE_KEY,
		
		MAX_BUFFER_SIZE: MAX_BUFFER_SIZE,
};